/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/303ynovpUKo
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"

export default function signup() {
  return (<>
    <header className="bg-gray-900 px-4 py-3 shadow dark:bg-gray-950">
      <div className="container mx-auto flex items-center justify-between">
        <Link className="flex items-center space-x-2 text-white" href="#">
          <MountainIcon className="h-6 w-6" />
          <span>{`IfIf}`}</span>
        </Link>
        <nav className="hidden space-x-4 md:flex">
          <Link className="text-gray-300 hover:text-white" href="#">
            Home
          </Link>
          <Link className="text-gray-300 hover:text-white" href="#">
            About
          </Link>
          <Link className="text-gray-300 hover:text-white" href="#">
            Services
          </Link>
          <Link className="text-gray-300 hover:text-white" href="#">
            Contact
          </Link>
        </nav>
        <Button className="hidden md:inline-flex" variant="primary">
          Sign Up
        </Button>
      </div>
    </header>
    <div
      className="flex min-h-[100dvh] items-center justify-center bg-gray-100 px-4 py-12 dark:bg-gray-950">
      <div className="mx-auto w-full max-w-md space-y-8">
        <div className="text-center">
          <h2
            className="text-3xl font-bold tracking-tight text-gray-900 dark:text-gray-50">
            Welcome! Join Our Member
          </h2>
          <p className="mt-2 text-sm text-gray-600 dark:text-gray-400">
            Get started with our platform and unlock new possibilities.
          </p>
        </div>
        <form action="#" className="space-y-6" method="POST">
          <div>
            <Label htmlFor="name">Full Name</Label>
            <Input
              autoComplete="name"
              id="name"
              name="name"
              placeholder="John Doe"
              required
              type="text" />
            <div className="text-red-500 font-medium">Error message goes here</div>
          </div>
          <div>
            <Label htmlFor="email">Email address</Label>
            <Input
              autoComplete="email"
              id="email"
              name="email"
              placeholder="you@example.com"
              required
              type="email" />
            <div className="text-red-500 font-medium">Error message goes here</div>
          </div>
          <div>
            <Label htmlFor="phone">Phone Number</Label>
            <Input
              autoComplete="tel"
              id="phone"
              name="phone"
              placeholder="(123) 456-7890"
              required
              type="tel" />
            <div className="text-red-500 font-medium">Error message goes here</div>
          </div>
          <div>
            <Label htmlFor="password">Password</Label>
            <Input
              autoComplete="current-password"
              id="password"
              name="password"
              placeholder="••••••••"
              required
              type="password" />
            <div className="text-red-500 font-medium">Error message goes here</div>
          </div>
          <Button className="w-full" type="submit">
            Sign up
          </Button>
        </form>
      </div>
    </div>
    <footer className="bg-gray-900 px-4 py-6 text-gray-400 dark:bg-gray-950">
      <div
        className="container mx-auto flex flex-col items-center justify-between space-y-4 md:flex-row md:space-y-0">
        <div className="flex items-center space-x-2">
          <MountainIcon className="h-6 w-6" />
          <span className="text-lg font-bold text-white">Acme Inc</span>
        </div>
        <nav className="flex space-x-4">
          <Link className="text-gray-400 hover:text-white" href="#">
            Home
          </Link>
          <Link className="text-gray-400 hover:text-white" href="#">
            About
          </Link>
          <Link className="text-gray-400 hover:text-white" href="#">
            Services
          </Link>
          <Link className="text-gray-400 hover:text-white" href="#">
            Contact
          </Link>
        </nav>
        <p className="text-sm">© 2024 Acme Inc. All rights reserved.</p>
      </div>
    </footer>
  </>);
}

function MountainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>)
  );
}
